[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.devnet]
launchr = "AD9VheLMqVPwbDQc5CmSHmCZdfa8CGmr2xXmhhNSTyhK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000

[test.validator]
url = "https://api.devnet.solana.com"

# Clone Orbit Finance program for testing graduation
[[test.validator.clone]]
address = "Fn3fA3fjsmpULNL7E9U79jKTe1KHxPtQeWdURCbJXCnM"

# Clone Token Program
[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

# Clone Associated Token Program  
[[test.validator.clone]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
